/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarIdRouteImport } from './routes/validar.$id'
import { Route as ApiUpaSearchRouteImport } from './routes/api/upa-search'
import { Route as ApiDescribeRouteImport } from './routes/api/describe'
import { Route as ApiClinicaRouteImport } from './routes/api/clinica'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNovoRouteImport } from './routes/_authenticated/novo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarIdRoute = ValidarIdRouteImport.update({
  id: '/validar/$id',
  path: '/validar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpaSearchRoute = ApiUpaSearchRouteImport.update({
  id: '/api/upa-search',
  path: '/api/upa-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDescribeRoute = ApiDescribeRouteImport.update({
  id: '/api/describe',
  path: '/api/describe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClinicaRoute = ApiClinicaRouteImport.update({
  id: '/api/clinica',
  path: '/api/clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovoRoute = AuthenticatedNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/clinica': typeof ApiClinicaRoute
  '/api/describe': typeof ApiDescribeRoute
  '/api/upa-search': typeof ApiUpaSearchRoute
  '/validar/$id': typeof ValidarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/novo': typeof AuthenticatedNovoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/clinica': typeof ApiClinicaRoute
  '/api/describe': typeof ApiDescribeRoute
  '/api/upa-search': typeof ApiUpaSearchRoute
  '/validar/$id': typeof ValidarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/novo': typeof AuthenticatedNovoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/clinica': typeof ApiClinicaRoute
  '/api/describe': typeof ApiDescribeRoute
  '/api/upa-search': typeof ApiUpaSearchRoute
  '/validar/$id': typeof ValidarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/novo'
    | '/perfil'
    | '/api/clinica'
    | '/api/describe'
    | '/api/upa-search'
    | '/validar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/novo'
    | '/perfil'
    | '/api/clinica'
    | '/api/describe'
    | '/api/upa-search'
    | '/validar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/novo'
    | '/_authenticated/perfil'
    | '/api/clinica'
    | '/api/describe'
    | '/api/upa-search'
    | '/validar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiClinicaRoute: typeof ApiClinicaRoute
  ApiDescribeRoute: typeof ApiDescribeRoute
  ApiUpaSearchRoute: typeof ApiUpaSearchRoute
  ValidarIdRoute: typeof ValidarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$id': {
      id: '/validar/$id'
      path: '/validar/$id'
      fullPath: '/validar/$id'
      preLoaderRoute: typeof ValidarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upa-search': {
      id: '/api/upa-search'
      path: '/api/upa-search'
      fullPath: '/api/upa-search'
      preLoaderRoute: typeof ApiUpaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/describe': {
      id: '/api/describe'
      path: '/api/describe'
      fullPath: '/api/describe'
      preLoaderRoute: typeof ApiDescribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clinica': {
      id: '/api/clinica'
      path: '/api/clinica'
      fullPath: '/api/clinica'
      preLoaderRoute: typeof ApiClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/novo': {
      id: '/_authenticated/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof AuthenticatedNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNovoRoute: typeof AuthenticatedNovoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNovoRoute: AuthenticatedNovoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiClinicaRoute: ApiClinicaRoute,
  ApiDescribeRoute: ApiDescribeRoute,
  ApiUpaSearchRoute: ApiUpaSearchRoute,
  ValidarIdRoute: ValidarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
